### ISSUE TITLE
Node Process crashed due to triggerUncaughtException

### ISSUE THREAD

**Issue by Alivers** [pyth-network/pyth-js#85]
Hello, you guys. I use `pyth-aptos-js` in my node project to fetch coin price. But when the request timeout(10s), node Process crashed due to triggerUncaughtException.  Is there any help or information I can follow to figure out what happened or fix the problem. Thanks for your reading and work. 
```ts
// constructor
    this.aptosPriceConn = new AptosPriceServiceConnection(this.config.config.pythMainnetEndpoint, {
      timeout: 10000,
      httpRetries: 0,
    });

// use (Catch the exception)
this.aptosPriceConn
            .getLatestPriceFeeds([pythPriceId])
            .then((feeds) => {
              if (feeds && feeds.length > 0) {
                const priceCfg = feeds[0].getPriceUnchecked();

                const p = Big(priceCfg.price).mul(Big(10).pow(priceCfg.expo));

                if (p.gt(0)) {
                  this.logger.debug(`pyth, ${pythPriceId} price = ${p.toString()}`);
                  return p.toNumber();
                }
              }

              throw `can't fetch price from pyth, pythPriceId=${pythPriceId}`;
            })
            .catch((reason) => {
              this.logger.error(
                `error occurs when getCoinPrice from pyth, pythPriceId=${pythPriceId}, reason: %o`,
                reason,
              );
              throw reason;
            });
```

The catch block logged the error msg expectly, but the node crashed by `triggerUncaughtException`.

```bash
{"level":50,"time":1675693965785,"pid":42,"hostname":"api-7d5f5b8857-jpx52","context":"PythPriceFetcher","msg":"error occurs when getCoinPrice from pyth, pythPriceId=0xef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d, 
reason: {
\"message\":\"timeout of 10000ms exceeded\",
\"name\":\"Error\",
\"stack\":\"Error: timeout of 10000ms exceeded
 at createError (/workspace/api-service/srv/main.cjs:87147:20)
 at RedirectableRequest.handleRequestTimeout (/workspace/api-service/srv/main.cjs:87815:20)
at RedirectableRequest.emit (node:events:513:28)\n    
at Timeout.<anonymous> (/workspace/api-service/srv/main.cjs:64949:17)\n    
at listOnTimeout (node:internal/timers:569:17)\n    
at process.processTimers (node:internal/timers:512:7)\",
\"config\":{\"transitional\":{\"silentJSONParsing\":true,\"forcedJSONParsing\":true,\"clarifyTimeoutError\":false},\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":10000,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1,\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"User-Agent\":\"axios/0.26.1\"},\"baseURL\":\"https://xc-mainnet.pyth.network\",\"params\":{\"ids\":[\"0xef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d\"],\"verbose\":false},\"method\":\"get\",\"url\":\"/api/latest_price_feeds\",\"axios-retry\":{\"retryCount\":0,\"lastRequestTime\":1675693955711}},\"code\":\"ECONNABORTED\",\"status\":null}"}

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: timeout of 10000ms exceeded
    at createError (/workspace/api-service/srv/main.cjs:87147:20)
    at RedirectableRequest.handleRequestTimeout (/workspace/api-service/srv/main.cjs:87815:20)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/workspace/api-service/srv/main.cjs:64949:17)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 10000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.26.1'
    },
    baseURL: 'https://xc-mainnet.pyth.network',
    params: {
      ids: [
        '0xef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d'
      ],
      verbose: false
    },
    method: 'get',
    url: '/api/latest_price_feeds',
    'axios-retry': { retryCount: 0, lastRequestTime: 1675693955711 },
    data: undefined
  },
  code: 'ECONNABORTED',
    _currentUrl: 'https://xc-mainnet.pyth.network/api/latest_price_feeds?ids[]=0xef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d&verbose=false',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

Node.js v18.14.0
 ELIFECYCLE  Command failed with exit code 1.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Alivers** [comment]
@ali-bahjati Thanks for your reply. Actually, I have no response time requirement, but want to fix the crash problem to prevent service from unavailable.
